format_version: 10
pipelines:
  UI-CD-YAML:
    group: enterpriseGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 1
    materials:
      git-frontend:
        git: https://github.com/Vamsi-PrimeSoft/ui.git
        username: Vamsi-PrimeSoft
        shallow_clone: false
        auto_update: true
        branch: main
        encrypted_password: AES:CvqRgCac0f8DmOI58hCnLA==:lMJcCvSj3nsKR5i/qjAJUA==
    parameters:
      TARGET_ENVIRONMENT: production
    variables:
      SFTP_HOST: 172.16.7.121
      SFTP_USER: ubuntu
      SFTP_REMOTE_PATH: /home/ubuntu
      LOCAL_DOWNLOAD_PATH: /var/go/downloads
      UNZIP_DESTINATION: /var/www/html
      FILE_OWNER: ubuntu:ubuntu
      TARGET_HOST: 192.168.56.126
      NOTIFY_CHANNEL: "#deployments"
    stages:
      - Deploy-Frontend:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: manual
          jobs:
            run-commands:
              timeout: 600
              resources:
                - ubuntu-agent
              environment_variables:
                SFTP_HOST: ${SFTP_HOST}
                SFTP_USER: ${SFTP_USER}
                SFTP_REMOTE_PATH: ${SFTP_REMOTE_PATH}
                LOCAL_DOWNLOAD_PATH: ${LOCAL_DOWNLOAD_PATH}
                UNZIP_DESTINATION: ${UNZIP_DESTINATION}
                FILE_OWNER: ${FILE_OWNER}
                TARGET_HOST: ${TARGET_HOST}
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        echo "[INFO] Checking OS release:"
                        cat /etc/os-release
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        echo "[INFO] Checking hostname:"
                        hostname
                - exec:
                    command: sudo
                    arguments:
                      - /bin/systemctl
                      - stop
                      - apache2.service
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        echo "[INFO] Downloading artifacts from SFTP..."
                        sftp -o StrictHostKeyChecking=no -i /var/go/.ssh/id_rsa ${SFTP_USER}@${SFTP_HOST} <<EOF
                        get ${SFTP_REMOTE_PATH}/*.zip ${LOCAL_DOWNLOAD_PATH}
                        bye
                        EOF
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        echo "[INFO] Unzipping artifacts..."
                        sudo rm -rf ${UNZIP_DESTINATION}/prime-square
                        sudo chown ${FILE_OWNER} ${LOCAL_DOWNLOAD_PATH}/*.zip
                        sudo unzip -o ${LOCAL_DOWNLOAD_PATH}/*.zip -d ${UNZIP_DESTINATION}
                        sudo mv ${LOCAL_DOWNLOAD_PATH}/*.zip /home/ubuntu/ui-archive
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        echo "[INFO] Updating environment configurations..."
                        sudo sed -i "s/ps-targethost:3804/${TARGET_HOST}/g" ${UNZIP_DESTINATION}/prime-square/main*.js
                        sudo sed -i "s/ps-targethost:3804/${TARGET_HOST}/g" ${UNZIP_DESTINATION}/prime-square/assets/environment/environment.json
                - exec:
                    command: sudo
                    arguments:
                      - /bin/systemctl
                      - restart
                      - apache2.service
                - exec:
                    command: echo
                    arguments:
                      - "Frontend deployment complete."
