format_version: 10
pipelines:
  UI-CD-YAML:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-878c2de:
        git: https://github.com/Vamsi-PrimeSoft/ui.git
        username: Vamsi-PrimeSoft
        shallow_clone: false
        auto_update: true
        branch: main
        encrypted_password: AES:CvqRgCac0f8DmOI58hCnLA==:lMJcCvSj3nsKR5i/qjAJUA==
    parameters:
      baseUiUrl: "192.168.56.126"
    stages:
      - Deploy-Frontend:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            run-commands:
              timeout: 0
              resources:
               - ubuntu-agent
              tasks:
                - exec:
                      command: sudo
                      arguments:
                        - /bin/systemctl
                        - stop
                        - apache2.service
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        sftp -o StrictHostKeyChecking=no -i /var/go/.ssh/id_rsa ubuntu@172.16.7.121 <<EOF
                        get /home/ubuntu/*.zip /var/go
                        bye
                        EOF
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        sudo chown ubuntu:ubuntu /var/go/*.zip
                        sudo unzip -o /var/go/*.zip -d /var/www/html
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        sudo sed -i "s/ps-targethost:3804/192.168.56.126/g" /var/www/html/prime-square/main*.js
                        sudo sed -i "s/ps-targethost:3804/192.168.56.126/g" /var/www/html/prime-square/assets/environment/environment.json

                - exec:
                      command: sudo
                      arguments:
                        - /bin/systemctl
                        - restart
                        - apache2.service
                - exec:
                    command: echo
                    arguments:
                      - "Frontend deployment complete."
