format_version: 10
pipelines:
  UI-CD-YAML:
    group: enterpriseGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 1
    materials:
      git-frontend:
        git: https://github.com/Vamsi-PrimeSoft/ui.git
        username: Vamsi-PrimeSoft
        shallow_clone: false
        auto_update: true
        branch: main
        encrypted_password: AES:CvqRgCac0f8DmOI58hCnLA==:lMJcCvSj3nsKR5i/qjAJUA==
    stages:
      - Deploy-Frontend:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: manual
          jobs:
            run-commands:
              timeout: 600
              resources:
                - ubuntu-agent
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        echo "[INFO] Checking OS release and hostname..."
                        cat /etc/os-release || { echo "[ERROR] Failed to check OS release"; exit 1; }
                        hostname || { echo "[ERROR] Failed to fetch hostname"; exit 1; }
                        
                        echo "[INFO] Stopping Apache service..."
                        sudo systemctl stop apache2.service || { echo "[ERROR] Failed to stop Apache"; exit 1; }
                        
                        
                        echo "[INFO] Unzipping artifacts..."
                        sudo rm -rf ${UNZIP_DESTINATION}/prime-square
                        sudo chown ${FILE_OWNER} ${LOCAL_DOWNLOAD_PATH}/*.zip
                        sudo unzip -o ${LOCAL_DOWNLOAD_PATH}/*.zip -d ${UNZIP_DESTINATION} || { echo "[ERROR] Failed to unzip artifacts"; exit 1; }
                        sudo mv ${LOCAL_DOWNLOAD_PATH}/*.zip /home/ubuntu/ui-archive
                        
                        echo "[INFO] Updating environment configurations..."
                        sudo sed -i "s/ps-targethost:3804/${TARGET_HOST}/g" ${UNZIP_DESTINATION}/prime-square/main*.js || \
                        { echo "[ERROR] Failed to update main.js configurations"; exit 1; }
                        sudo sed -i "s/ps-targethost:3804/${TARGET_HOST}/g" ${UNZIP_DESTINATION}/prime-square/assets/environment/environment.json || \
                        { echo "[ERROR] Failed to update environment.json configurations"; exit 1; }
                        
                        echo "[INFO] Restarting Apache service..."
                        sudo systemctl restart apache2.service || { echo "[ERROR] Failed to restart Apache"; exit 1; }
                        
                        echo "[INFO] Frontend deployment complete."
    parameters:
      SFTP_HOST: 172.16.7.121
      SFTP_USER: ubuntu
      SFTP_REMOTE_PATH: /home/ubuntu
      LOCAL_DOWNLOAD_PATH: /var/go/downloads
      UNZIP_DESTINATION: /var/www/html
      FILE_OWNER: ubuntu:ubuntu
      TARGET_HOST: 192.168.56.126
