format_version: 10
pipelines:
  UI-CD-YAML:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-878c2de:
        git: ${GIT_REPO_URL}
        username: ${GIT_USERNAME}
        shallow_clone: false
        auto_update: true
        branch: ${GIT_BRANCH}
        encrypted_password: ${GIT_ENCRYPTED_PASSWORD}
    parameters:
      baseUiUrl: "${BASE_UI_URL}"
      gitRepoUrl: "https://github.com/Vamsi-PrimeSoft/ui.git"
      gitUsername: "Vamsi-PrimeSoft"
      gitBranch: "main"
      gitEncryptedPassword: "AES:CvqRgCac0f8DmOI58hCnLA==:lMJcCvSj3nsKR5i/qjAJUA=="
      sftpHost: "172.16.7.121"
      sftpUser: "ubuntu"
      sftpKeyPath: "/var/go/.ssh/id_rsa"
      sftpRemotePath: "/home/ubuntu/*.zip"
      localDownloadPath: "/var/go"
      unzipDestination: "/var/www/html"
      apacheService: "apache2.service"
      fileOwner: "ubuntu:ubuntu"
      targetHost: "192.168.56.126"
    stages:
      - Deploy-Frontend:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            run-commands:
              timeout: 0
              resources:
               - ubuntu-agent
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        echo "Checking OS release:"
                        cat /etc/os-release
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        echo "Checking hostname:"
                        hostname
                - exec:
                      command: sudo
                      arguments:
                        - /bin/systemctl
                        - stop
                        - ${APACHE_SERVICE}
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        sftp -o StrictHostKeyChecking=no -i ${SFTP_KEY_PATH} ${SFTP_USER}@${SFTP_HOST} <<EOF
                        get ${SFTP_REMOTE_PATH} ${LOCAL_DOWNLOAD_PATH}
                        bye
                        EOF
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        sudo chown ${FILE_OWNER} ${LOCAL_DOWNLOAD_PATH}/*.zip
                        sudo unzip -o ${LOCAL_DOWNLOAD_PATH}/*.zip -d ${UNZIP_DESTINATION}
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        sudo sed -i "s/ps-targethost:3804/${TARGET_HOST}/g" ${UNZIP_DESTINATION}/prime-square/main*.js
                        sudo sed -i "s/ps-targethost:3804/${TARGET_HOST}/g" ${UNZIP_DESTINATION}/prime-square/assets/environment/environment.json

                - exec:
                      command: sudo
                      arguments:
                        - /bin/systemctl
                        - restart
                        - ${APACHE_SERVICE}
                - exec:
                    command: echo
                    arguments:
                      - "Frontend deployment complete."
