format_version: 10
pipelines:
  UI-CD-YAML:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-878c2de:
        git: https://github.com/Vamsi-PrimeSoft/ui.git
        username: Vamsi-PrimeSoft
        shallow_clone: false
        auto_update: true
        branch: main
        encrypted_password: AES:CvqRgCac0f8DmOI58hCnLA==:lMJcCvSj3nsKR5i/qjAJUA==
    stages:
      - Deploy-Frontend:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            run-commands:
              timeout: 0
              resources:
               - ubuntu-agent
              variables:
                SFTP_SERVER: 172.16.7.121
                APP_SERVER: 192.168.56.126
                SFTP_USER: ubuntu
                SFTP_KEY_PATH: /var/go/.ssh/id_rsa
                SFTP_DIR: /home/ubuntu
                GOCD_DIR: /home/ubuntu
                APP_SERVER_BUILD_DIR: /home/ubuntu/builds/ui
                APP_SERVER_TARGET_DIR: /var/www/html/prime-square
              tasks:
                - exec:
                    command: sudo
                    arguments:
                      - mkdir
                      - -p
                      - ${GOCD_DIR}
                - exec:
                    command: sudo
                    arguments:
                      - chown
                      - go:go
                      - ${GOCD_DIR}
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        sftp -o StrictHostKeyChecking=no -i /var/go/.ssh/id_rsa ubuntu@172.16.7.121 <<EOF
                        get /home/ubuntu/*.zip /home/ubuntu
                        bye
                        EOF
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        sftp -o StrictHostKeyChecking=no -i /var/go/.ssh/id_rsa go@192.168.56.126 <<EOF
                        put ${GOCD_DIR}/*.zip ${APP_SERVER_BUILD_DIR}/
                        bye
                        EOF
                - exec:
                    command: bash
                    arguments:
                      - -c
                      - |
                        ssh -i /var/go/.ssh/id_rsa ubuntu@${APP_SERVER} <<EOF
                        sudo mkdir -p ${APP_SERVER_TARGET_DIR}
                        sudo chown ubuntu:ubuntu ${APP_SERVER_BUILD_DIR}/*.zip
                        sudo unzip -o ${APP_SERVER_BUILD_DIR}/*.zip -d ${APP_SERVER_TARGET_DIR}
                        EOF
                - exec:
                    command: echo
                    arguments:
                      - "Frontend deployment complete."
